mission_index:
    path:     /index
    defaults: { _controller: "MissionBundle:Mission:index" }
    methods:  GET

mission_show:
    path:     /{id}/show
    defaults: { _controller: "MissionBundle:Mission:show" }
    methods:  GET
mission_create:
    path:     /create
    defaults: { _controller: "MissionBundle:Mission:create" }



