<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_user.user_checker' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\User\\UserCheckerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\User\\UserChecker.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\user-bundle\\Security\\UserChecker.php';

return $this->services['fos_user.user_checker'] = new \FOS\UserBundle\Security\UserChecker();
