<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCh1zyqf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCh1zyqf/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCh1zyqf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCh1zyqf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCh1zyqf\appProdProjectContainer([
    'container.build_hash' => 'Ch1zyqf',
    'container.build_id' => 'e188d0ab',
    'container.build_time' => 1549574012,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCh1zyqf');
