<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV8kz0io\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV8kz0io/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerV8kz0io.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerV8kz0io\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerV8kz0io\appDevDebugProjectContainer([
    'container.build_hash' => 'V8kz0io',
    'container.build_id' => 'c6331a99',
    'container.build_time' => 1549813515,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV8kz0io');
