<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRfbkexi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRfbkexi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRfbkexi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRfbkexi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRfbkexi\appDevDebugProjectContainer([
    'container.build_hash' => 'Rfbkexi',
    'container.build_id' => 'ed044e49',
    'container.build_time' => 1549620153,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRfbkexi');
